ignore some errors
archlinux
4.12.4-1-ARCH x86_64 Linux

cp -f os/linux/Makefile.6 /home/admin/pj/Netgear-A6210/os/linux/Makefile
make -C /lib/modules/4.12.4-1-ARCH/build DBGFLAGS=-DDBG SUBDIRS=/home/admin/pj/Netgear-A6210/os/linux modules
make[1]: Entering directory '/usr/lib/modules/4.12.4-1-ARCH/build'
  CC [M]  /home/admin/pj/Netgear-A6210/os/linux/../../os/linux/cfg80211/cfg80211.o
/home/admin/pj/Netgear-A6210/os/linux/../../os/linux/cfg80211/cfg80211.c:2385:25: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .change_virtual_intf = CFG80211_OpsVirtualInfChg,
                         ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/admin/pj/Netgear-A6210/os/linux/../../os/linux/cfg80211/cfg80211.c:2385:25: note: (near initialization for ‘CFG80211_Ops.change_virtual_intf’)
/home/admin/pj/Netgear-A6210/os/linux/../../os/linux/cfg80211/cfg80211.c:2386:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .add_virtual_intf = CFG80211_OpsVirtualInfAdd,
                      ^~~~~~~~~~~~~~~~~~~~~~~~~
 Changes to be committed:
	modified:   os/linux/cfg80211/cfg80211.c
	modified:   os/linux/cfg80211/cfg80211_inf.c

よくわからないけれどこのあたりをコメントアウトするとビルドが通って良い塩梅になる